### ISSUE TITLE
Array_key_exists() expects parameter 2 to be array, integer given

### ISSUE THREAD

**Issue by ghost** [damanic/ls1-module-updatecenter#1]
After installing, patching and attached the repo with the new update centre module, logging out and logging back there seems to be an error when going to **[BACKEND_URL]/system/settings/**

On line #127 in to **/modules/core/classes/core_modulemanager.php** in the _groupSettingsItems($items)_ method **$item** (from the foreach) is being passed as an integer rather than an array to **array_key_exists()**.

As a work around: 
**$section = is_array($item) && array_key_exists('section', $item)? $item['section'] : $misc_title;**

![screen shot 2015-11-18 at 09 34 10](https://cloud.githubusercontent.com/assets/15346361/11238199/f349b648-8ddb-11e5-8831-bbfabd930619.png)

**Comment by damanic** [comment]
core_modulemanager.php on my repo has not changed from the last official lemonstand release.  Perhaps you modified this file before and the update undone your patch?  

I suspect there is a module on your install that is not conventional which causes this error.
All your module_class.php files should have `public function listSettingsItems()` return an array of arrays

eg.

```
    public function listSettingsItems()
    {
        $result = array(
            array(
                'icon'=>'/modules/updatecenter/resources/images/fork.png',
                'title'=>'Repo Updates',
                'url'=>'/updatecenter/setup',
                'description'=>'Configure options to update modules from public repositories',
                'sort_id'=>250,
                'section'=>'System'
            ),1
        );

        return $result;
    }
```

That said, I may still add your `is_array()` suggestion to make the `groupSettingsItems($items)` method more tolerant. 

Thanks.

**Comment by ghost** [comment]
Yes, I did wonder and start to suspect the same, on the other hand however this issue only occurred after I installed the Update Centre Module, but if the official core didn't have it, I will assume it is an issue on my store and will got through my modules make sure all is ok.

**Comment by samtempledev** [comment]
I too am experiencing this issue from blank install of lemonstand

I had to put this:

```
$section = is_array($item) && array_key_exists('section', $item)? $item['section'] : $misc_title;
```

**Comment by damanic** [comment]
I will update. A blank/default install (no extra modules) taken from last official lemonstand release produced this error?

**Comment by samtempledev** [comment]
Actually looks like I had a few modules bound, gallery, contact and tweak...

**Comment by samtempledev** [comment]
Will you roll out your updates to the lemonstand market place?

**Comment by damanic** [comment]
Only to fix issues that may prevent a market place install getting the latest release from github.

**Comment by damanic** [comment]
Well mystery solved, and it was staring me in the face the whole time.

In the copy of public function listSettingsItems() further up the comments you can see the number 1 found its way into the array.  How I didn't see that......

Anyway fixed in last commit...  this issue is properly closed.
