### ISSUE TITLE
Lemonstand reports no updates available, when there are

### ISSUE THREAD

**Issue by n0rbie** [damanic/ls1-module-updatecenter#11]
Hi Matt

As mentioned on the Lemonstand forum thread (http://forum.lemonstand.com/topic/7120-urgent-lemonstand-v1-vulnerability/) upon installing update center and checking for updates within Lemonstand, it shows that there are no updates available.

This behaviour is the same for two Lemonstand installations on the same hosting platform so I agree that it sounds server related. If you could help with troubleshooting this, it would be much appreciated!

Many thanks

**Comment by damanic** [comment]
Hi norbie,

Can you add some traceLogs to
/modules/updatecenter/classes/updatecenter_module.php

Replace functions with (or just add the tracelogs as shown)

```
    public function override_ls_versions($data){
        traceLog('override_ls_versions');
        if(isset($data['modules'])) {
            foreach ( $data['modules'] as $module_name => $version ) {

                if ( UpdateCenter_Config::is_core_module( $module_name ) ) {
                    if ( !UpdateCenter_Helper::is_old_ls_version( $module_name, $version ) ) {
                        //Avoid errors: always send last ls version to lemonstand update center if up to date with final official release.
                        $data['modules'][$module_name] = UpdateCenter_Config::get_last_ls_version( $module_name );
                    }
                }

                if ( UpdateCenter_Config::get()->is_blocked_module( $module_name ) ) {
                    unset( $data['modules'][$module_name] );
                }

            }
        }
        traceLog($data);
        return $data;
    }
```

And

```
    public function add_repository_updates($data){
        traceLog('add_repository_updates');
        $data['force'] = $data['force'] ? true : false;
        $config = UpdateCenter_Config::get();

        if(!$config->has_active_repository()){
            traceLog('add_repository_updates: no active repository');
            return $data;
        }

        $config = UpdateCenter_Config::get();
        $repo = new UpdateCenter_Repository();
        $updates = $repo->get_repository_updates($data['force']);

        if(!count($updates)){
            traceLog('add_repository_updates: no get_repository_updates');
            return $data;
        }

        foreach($updates as $module_name => $obj){
            $data['update_list']['data'][$module_name] = $obj;
        }
        traceLog($data);
        return $data;
    }
```

When done, check for updates. Then go to /logs/info.txt (or whatever file you have setup in config for  `CONFIG['TRACE_LOG']['INFO']`)  and report back on output.

If nothing added to the tracelog then your install is not firing the required events, which would be interesting considering the UC status tab shows install as compatible.

**Comment by n0rbie** [comment]
Thanks Matt, here's the output:

```
[2016-08-01 09:33:25] override_ls_versions
[2016-08-01 09:33:25] Array
(
    [modules] => Array
        (
            [backend] => 1.9.29
            [blog] => 1.0.47
            [cms] => 1.10.37
            [contact] => 0.1.1
            [core] => 1.11.97
            [gallery] => 0.0.5
            [googleanalytics] => 1.0.4
            [profile] => 1.0.3
            [shop] => 1.25.138
            [sitemap] => 1.4.0
            [system] => 1.3.13
            [updatecenter] => 1.2.15
            [users] => 1.0.25
        )

)

[2016-08-01 09:33:26] add_repository_updates
[2016-08-01 09:33:28] add_repository_updates: no get_repository_updates
[2016-08-01 09:33:48] override_ls_versions
[2016-08-01 09:33:48] Array
(
    [modules] => Array
        (
            [backend] => 1.9.29
            [blog] => 1.0.47
            [cms] => 1.10.37
            [contact] => 0.1.1
            [core] => 1.11.97
            [gallery] => 0.0.5
            [googleanalytics] => 1.0.4
            [profile] => 1.0.3
            [shop] => 1.25.138
            [sitemap] => 1.4.0
            [system] => 1.3.13
            [updatecenter] => 1.2.15
            [users] => 1.0.25
        )

)
```

**Comment by damanic** [comment]
ok you can remove those tracelogs...

update the get_latest_version_number() function in
/modules/updatecenter/classes/updatecenter_repository_github.php
to

```
    public function get_latest_version_number($module_name){
        try {
            $repo_data = $this->get_latest_version( $module_name );
            return $repo_data['tag_name'];
        } catch (Exception $e){
            traceLog($e->getMessage());
            throw new Exception($e->getMessage());
        }
    }
```

then check for updates. If it is going wrong here, it will throw an error either to screen or to your tracelog that should point us towards the cause.

**Comment by n0rbie** [comment]
You star!

That threw this exception on screen:

`Fatal error: Call to undefined function Exception() in /var/sites/s/stickerblimp.com/public_html/modules/updatecenter/classes/updatecenter_repository_github.php on line 42`

And in the info.txt log:

`[2016-08-01 10:37:34] Message from GitHub: API rate limit exceeded for x.x.x.x (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

Which of course led me to create a personal access token on GitHub, enter it into the Repo Updates settings and hey presto, it worked! I can now update!

Thank you so much for your help!

**Comment by damanic** [comment]
Ah good. The fatal error was my typo but you got what was needed in the tracelog so all good. 

Pretty sure there was a reason I suppressed those errors, but they would be useful in the tracelog with a note in readme for troubleshooting - which I will add. Thanks.
