### ISSUE TITLE
Undefined variable: ls_files 

### ISSUE THREAD

**Issue by jimbolinos** [damanic/ls1-module-updatecenter#13]
Hi Matt - Just came to update and am getting the error: 

Undefined variable: ls_files 

Any clues?

Thanks for your continued work.

**Comment by damanic** [comment]
Most likely a folder/file write permission or communication issue. Check the status tab in `Settings -> Repo Updates`

**Comment by jimbolinos** [comment]
Hi Matt, I'm seeing the below, which I think means everything is OK? The Core is updated to **1.13.9**

_Write Access:
Modules Directory Writable

Core Compatibility Status:
If you are running the last lemonstand release of the core module you will need to update it for repository updates to work. If presented, the update button below will patch your core module with the libs and events required to run this module. Alternatively you can copy/merge the latest core release that supports this module from github: https://github.com/damanic/ls1-module-core

Core Update Manager **Compatible**

Core Zip Helper **Compatible**

PclZip Library **Compatible**_

Many thanks

**Comment by jimbolinos** [comment]
Hi Matt,

I hope you're well. Just came to update again due to Flash ending and realised I never managed to get this to resolve. I have manually amended the core_updatemanager.php file with your fix, but the problem still persists.

If I attempt to run updates on all of the modules individualy, or together, the original error _Undefined variable: ls_files_ continues.

If I attempt to only update the updatecenter module only, I get the error _Undefined index: data_

These are the messages from the LS error log:
`Phpr_PhpException: Undefined variable: versions. In /.../classes/core_updatemanager.php, line 231`

`Phpr_PhpException: Undefined variable: ls_files. In /.../classes/core_updatemanager.php, line 286`

**UPDATE: It looks as if the main 'classes' updatemanager.php file wasn't being updated with your fix - upon doing this everything has worked perfectly.**

Best wishes,
James

**Comment by damanic** [comment]
Good to hear you got it up and running James!

Matt
