### ISSUE TITLE
Module Controller Cancel Button

### ISSUE THREAD

**Issue by ghost** [damanic/ls1-module-updatecenter#2]
When inside the Update Centre settings page (**[BACKEND_URL/updatecenter/setup/**), the cancel button doesn't cancel and redirect you back to the system settings page it keeps you inside the Update Centre settings page.

**<?= backend_ajax_button('Cancel', 'index_onCancel') ?>**
is better off as
**<?= backend_button('Cancel', url('system/settings')) ?>**

**Comment by damanic** [comment]
Agree. Merged your pull request. 

I will also remove `protected function index_onCancel()` from UpdateCenter_Setup

Thanks
