### ISSUE TITLE
updateCenter_Helper::is_old_ls_version()

### ISSUE THREAD

**Issue by samtempledev** [damanic/ls1-module-updatecenter#4]
Non-static method updateCenter_Helper::is_old_ls_version() should not be called statically, assuming $this from incompatible context

I am getting this error when clicking the check for updates button...

**Comment by samtempledev** [comment]
```
public function is_old_ls_version($module_name,$version){
```

had to change to this:

```
public static function is_old_ls_version($module_name,$version){
```

**Comment by damanic** [comment]
Yes it should have been declared static. Will push a fix...
