### ISSUE TITLE
Fork Module Updates

### ISSUE THREAD

**Issue by samtempledev** [damanic/ls1-module-updatecenter#5]
I have forked your repos to work on myself, when I create a repository config for carpydraws and point it to the forked repos I get a "Message from GitHub: Not Found"

``` php
array(
    'source' => 'github',
    'modules' => array(
        'core' => array(
            'owner' => 'carpydraws',
            'repo' => 'ls1-module-core'
        ),
        'cms' => array(
            'owner' => 'carpydraws',
            'repo' => 'ls1-module-cms'
        ),
        'updatecenter' => array(
            'owner' => 'carpydraws',
            'repo' => 'ls1-module-updatecenter'
        )
    )
)
```

You can see here the links used in the code:

https://api.github.com/repos/damanic/ls1-module-cms/releases - this works

https://api.github.com/repos/carpydraws/ls1-module-cms/releases - this doesnt

**Comment by carpydraws** [comment]
Seems that if you have a fork then github api does not see any of the already made releases in the fork

**Comment by damanic** [comment]
It looks like the releases made on the parent repository are not considered releases on your fork, so they do not show up.  I suggest you do bleeding edge updates from your forks if you are testing your own changes and then issue pull requests if you think any of your changes benefit the parent repo. 

```
    $repository_info = array(
        'name'=>'Bleeding Edge Updates | github:carpydraws',
        'description'=>'Bleeding Edge Updates from carpydraws',

        'repositories' => array(
            array(
                'source' => 'github',
                'modules' => array(
                    'core' => array(
                        'owner' => 'carpydraws',
                        'repo' => 'ls1-module-core',
                        'git_use_branch' => 'master',
                    ),
                    'cms' => array(
                        'owner' => 'carpydraws',
                        'repo' => 'ls1-module-cms',
                        'git_use_branch' => 'master',
                    ),
                    'updatecenter' => array(
                        'owner' => 'carpydraws',
                        'repo' => 'ls1-module-updatecenter',
                        'git_use_branch' => 'master',
                    )
                )
            )

        ),

    );
```

To apply bleeding edge updates you need to run 'Force Update'. Read 'Forced Updates' on the readme if you havent already. It will refresh ALL your modules: https://github.com/damanic/ls1-module-updatecenter

**Comment by damanic** [comment]
Hmm thinking about it, perhaps bleeding edge updates should allow you to independently specify the branch owner so that you can use the parent for release updates and your own fork for bleeding edge updates.

Eg.

```

      array(
            'source' => 'github',
            'modules' => array(
                'core' => array(
                    'owner' => 'damanic',
                    'repo' => 'ls1-module-core',
                    'edge_updates' => array( 
                        'owner' => 'carpydraws',
                        'repo' => 'ls1-module-core'
                        'branch' => 'master'
                    )
                ),
            ),

        );
```

Seem useful to you?

**Comment by samtempledev** [comment]
yes that would be useful, I did try the bleeding edge but seems you still have to first define your repos to get your current releases then change the settings to my own repos to get the master bleeding edge updates...

**Comment by damanic** [comment]
this has been added in latest version. see updated readme.md for config info
