### ISSUE TITLE
Can't check for updates

### ISSUE THREAD

**Issue by lfkiter** [damanic/ls1-module-updatecenter#6]
Please see this post.  Not sure how I am getting this error.
http://forum.lemonstand.com/topic/7115-update-center-github-updates/
![error](https://cloud.githubusercontent.com/assets/6294724/11694344/39c573fc-9e6f-11e5-9721-d032dd7fa614.png)

**Comment by damanic** [comment]
that is a very low level error notice ( E_NOTICE ) and I would suggest setting up to ignore them.

You can either turn off php error reporting for E_NOTICE
or try the lemonstand config file by setting it to something that does not include E_NOTICE, eg.
`$CONFIG['ERROR_REPORTING'] = E_ERROR;`

I will release an update with more checks to avoid `undefined index` notices.

**Comment by lfkiter** [comment]
Thanks! that did the trick!

**Comment by damanic** [comment]
Latest release v1.2.12 has more checks, so shouldn't give any E_NOTICE errors.
