### ISSUE TITLE
Table 'mowerman.updatecenter_config' doesn't exist

### ISSUE THREAD

**Issue by Legin76** [damanic/ls1-module-updatecenter#7]
After uploading updatecenter/ directory to the modules directory and running /backdoor/updatecenter/setup/ I get the following error.

MySQL error executing query: Table 'mowerman.updatecenter_config' doesn't exist

**Comment by damanic** [comment]
Lemonstand will run sql updates on login. Try logging out/in.

**Comment by Legin76** [comment]
That's sorted it.. Thanks.
